image: python2.7
script:
  - python setup.py develop && python setup.py test
services:
  - redis:2.6
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
